### ISSUE TITLE
[Discussion] DECQ Apollo/Saturn pack

### ISSUE THREAD

**Issue by PhineasFreak** [PhineasFreak/RealismOverhaul#2]
## Prerequisites:
* https://github.com/KSP-RO/RealismOverhaul/pull/1907
* https://github.com/KSP-RO/RealismOverhaul/pull/1908
* https://github.com/KSP-RO/RealismOverhaul/pull/1911
* https://github.com/KSP-RO/RealismOverhaul/pull/1912
* https://github.com/KSP-RO/RealismOverhaul/pull/1913
* https://github.com/KSP-RO/RealismOverhaul/pull/1914

## Link to the RO configs:

* https://github.com/KSP-RO/RealismOverhaul/compare/master...PhineasFreak:RO-DECQ-Apollo-Saturn

**Comment by Asduffo** [comment]
Hi. I'm Zuppermati in the forums. Anyway: continuing the discussion from the forum:
If RT == Remote Tech, then yes I do have it installed. 

I also forgot:
The separator between the lem descent and ascent stage has node top and bottom inverted, so when I liftoff from the moon the ascent stage separates but it keeps the explosive bolts attached. A quick fix is simply inverting the nodes:

`    @node_stack_bottom = 0.0, 0.029, 0.0, 0.0, -1.0, 0.0, 2
    @node_stack_top = 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 2`

Also when I liftoff from the moon the separation makes the lem ascent stage rotate quite wild. It's not impossible to liftoff but you must be super ready at lem liftoff to stabilize it. Dunno what causes it.

one last minor issues is that the rover detaches quite violently from the lem (It's not a big deal but it gets shot away for a couple of meters XD)

**Comment by PhineasFreak** [comment]
I will take a look at the node, along with the confirmed SM RCS issue.

The LRV ejection force is intended to be large in order to push it as far as possible form the LM. If you try to deploy the LRV sometimes it gets stuck inside the LM with...explosive results. TL;DR it is intentional.

**Comment by PhineasFreak** [comment]
OK, both the SM RCS and the LEM decoupler bugs have been fixed (stupid copy & paste mistakes).

@Asduffo About the RT/animations interop: can you try and load the configs wthout RT installed. CommNet is fully configured for these parts, although i still have to make some tweaks on the ranges.

**Comment by leoalbuq** [comment]
Hi... I´ve tried everything but I can´t manage to make the SM RCS work... all the other things are ok an I have just the game, your configs of RO and the Saturn V installed

**Comment by Asduffo** [comment]
Hi sorry for the late reply. RCS now seems to work just fine. I didn't do an in-depth test coz I'm kinda busy this period but the lem looks like to be working fine as well. 
As a side note, removing remotetech doesn't fix the animations

**Comment by leoalbuq** [comment]
I´ll try it... by the time I was using the FASA ones with some adjustments on the tanks of the SM.

**Comment by leoalbuq** [comment]
I don´t know why but... the gimbal of the SPS engine don´t work after decouple of the SIVB... it´s very hard to do maneuvers with that bug... If you build the SM alone to test it, the gimbal works fine.

**Comment by PhineasFreak** [comment]
@Asduffo OK, i think i have tackled the animation bug. I also fixed the CommNet ranges, since they were too large and they were not taking into account the "multiple antenna multiplier" option.

**Comment by leoalbuq** [comment]
After the Bug fix pass #2 the SM RCS are working!!! :D The only thing left now its the SM SPS gimbal... its ever locked... all the rest of the rocket are working great

**Comment by PhineasFreak** [comment]
@leoalbuq The SPS engine gimbal works as expected. How did you activate your engine, though the staging stack or via right-clicking on it?

**Comment by leoalbuq** [comment]
I’m activating by right click... if I do this by staging it’ll work?

**Comment by PhineasFreak** [comment]
Yes, it is a KSP bug.

**Comment by PhineasFreak** [comment]
What do you mean by "I open the CM hatch and didn’t work..."? You can definitely EVA the Apollo CM crew via the **Crew Hatch** option. Otherwise, use the **EVA** button located on the crew portraits.

Do note that the LM hatch is not accessible from the outside and you will need to use the aforementioned **EVA** button.

**Comment by PhineasFreak** [comment]
Well, i tried it as part of the stock crew transfer functionality test and it worked. Do you use CLS?

**Comment by SlainteMaith** [comment]
What fixed the RCS issues?  I'm trying to position the S-IVB for lunar xfer, and the RCS doesn't work.  Enabling the ones on the SM don't work either.

**Comment by PhineasFreak** [comment]
RCS are staged, meaning that they will not work if you do not stage them via the staging list.

The SM RCS had a typo and was corrected in the "bugfix pass 1": https://github.com/KSP-RO/RealismOverhaul/commit/a07d3dd05cc1ddba6d8c7d1653a665833aa532bf
